# Site settings
title: II Open Xacobeo — Disc Golf Open
email: td@openxacobeo.com
url: https://www.openxacobeo.com/
description: "April 15-17, 2022 — Santiago de Compostela, Spain"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'
  red: '#bc0000'

# Footer settings
footer: Compostela Disc Golf Club

# Build settings
markdown: kramdown
permalink: pretty

# Multilanguage
plugins:
  - jekyll-multiple-languages-plugin

languages: ["en", "es", "gl"]
exclude_from_localizations: ["javascript", "img", "css", "video", "js", "files"]
default_locale_in_subfolder: true
